[dc01]
dc01 ansible_host=192.168.1.10

[dc01:vars]
ansible_user=Administrator
ansible_password='CHANGE_ME'
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore
